netsnmp/_api.h: commentout errored lines
```
3.10 -c netsnmp/session.c -o build/temp.linux-x86_64-cpython-310/netsnmp/session.o
      x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-310/netsnmp/_api.o build/temp.linux-x86_64-cpython-310/netsnmp/get.o build/temp.linux-x86_64-cpython-310/netsnmp/get_async.o build/temp.linux-x86_64-cpython-310/netsnmp/interface.o build/temp.linux-x86_64-cpython-310/netsnmp/session.o -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lnetsnmp -lm -lssl -lssl -lcrypto -lzmq -lczmq -o build/lib.linux-x86_64-cpython-310/netsnmp/_api.cpython-310-x86_64-linux-gnu.so
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/get.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: multiple definition of `SNMPError'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/get.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: multiple definition of `_debug_level'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/get_async.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: multiple definition of `_debug_level'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/get_async.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: multiple definition of `SNMPError'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/interface.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: multiple definition of `SNMPError'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/interface.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: multiple definition of `_debug_level'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/session.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: multiple definition of `_debug_level'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:13: first defined here
      /usr/bin/ld: build/temp.linux-x86_64-cpython-310/netsnmp/session.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: multiple definition of `SNMPError'; build/temp.linux-x86_64-cpython-310/netsnmp/_api.o:/tmp/pip-req-build-jscb7e3o/./netsnmp/_api.h:16: first defined here
```

doesn't work
```
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./netsnmp -I/opt/devconf3/.venv/include -I/usr/include/python3.10 -c netsnmp/_api.c -o build/temp.linux-x86_64-cpython-310/netsnmp/_api.o
      netsnmp/_api.c: In function ‘api_init’:
      netsnmp/_api.c:54:5: error: ‘SNMPError’ undeclared (first use in this function)
         54 |     SNMPError = PyErr_NewException("netsnmp._api.SNMPError", NULL, NULL);
            |     ^~~~~~~~~
      netsnmp/_api.c:54:5: note: each undeclared identifier is reported only once for each function it appears in
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
```

is it double imported?

Try static int.

Try change include order.

Python.h double included? -> no

What happens if i turn it to static?

Revert some changes that didn't really have effect.